services:
  youtube-slack:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: youtube-slack
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Seoul
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - CHECK_INTERVAL=1800
    restart: unless-stopped